<?php

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */
/**
 * Constants Permission/Menu/Theme
 */
define('MENU_BIBLIOGRAPHY_HOME', 'bibliography');
define('MENU_BIBLIOGRAPHY_CITATION', 'bibliography/citation');
define('MENU_BIBLIOGRAPHY_CITATION_SEARCH', 'bibliography/citation/search');
define('THEME_BIBLIOGRAPHY_FORM_TABLE', 'islandora_bibliography_form_table');

/**
 * The menu entries for this module.
 *
 * @return $menu_entries
 *   An arrray of the items to be added to the drupal menu
 */
function islandora_bibliography_menu() {
  $items = array();
  $items[MENU_BIBLIOGRAPHY_HOME] = array(
    'title' => t('Bibliography'),
    'description' => 'Here you can remove or export citations from your bibliography.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bibliography_form'),
    'access arguments' => array('access content'),
    'file' => 'BibliographyForm.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items[MENU_BIBLIOGRAPHY_CITATION] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bibliography_citation_form'),
    'access arguments' => array('access content'),
    'file' => 'CitationForm.inc',
    'type' => MENU_CALLBACK,
  );
  $items[MENU_BIBLIOGRAPHY_CITATION_SEARCH] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bibliography_citation_search_form'),
    'access arguments' => array('access content'),
    'file' => 'CitationForm.inc',
    'type' => MENU_CALLBACK,
  );
  $items['bibliography/citation/search/add'] = array(
    'page callback' => 'islandora_scholar_mylist_add',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 *  AHAH callback
 * to add items to my list
 */
function islandora_scholar_mylist_add() {
  module_load_include('inc', 'php_lib', 'Ahah');
  module_load_include('inc', 'islandora_bibliography', 'Bibliography');
  module_load_include('inc', 'islandora_bibliography', 'CitationForm');
  //bootstrap drupal
  //drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
  /*$post = $_POST;
  $add = $_POST['add'];
  $pid = $_POST['pid'];
  if(!isset($pid)){
    echo 'false';
    return;
  }
  if(isset($add) && $add == 'true'){
     Bibliography::AddCitation($pid);
  } else if(isset($add)){
     Bibliography::RemoveCitation($pid);
  }*/
  
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  $form = Ahah::processForm($form_id, $form, $form_state);

  $form_state['storage'] = NULL;
  $form_state['rebuild'] = TRUE;
  $form_state['submitted'] = FALSE;

  $pid = $form_state['post']['pid'];
  $stored = $form_state['post']['stored'];

  if ($form_state['post']['stored'] == TRUE) {
    
    Bibliography::RemoveCitation($pid);
    $form_state['values']['stored'] = FALSE;
  }
  else {
    Bibliography::AddCitation($pid);
    $form_state['values']['stored'] = TRUE;
  }
  
  $form_state['values']['procedure'] = '';
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  Ahah::respond($form['procedure']);
   
   
}

/**
 * Implements hook_theme().
 */
function islandora_bibliography_theme() {
  return array(
    THEME_BIBLIOGRAPHY_FORM_TABLE => array(
      'arguments' => array('element' => NULL),
      'file' => 'BibliographyForm.inc',
    )
  );
}