<?php

/**
 * @file
 *
 * Implements hooks and callbacks for this module.
 */

function citeproc_item_from_mods(DOMDocument $mods) {
  module_load_include('inc', 'citeproc', 'CiteProcJSItem');
  module_load_include('php', 'citeproc', 'generators/converter');
  $item = new CiteProcJSItem();
  $raw = convert_mods_to_citeproc_jsons($mods->saveXML());
  $item->set($raw);
  return $item;
}

function citeproc_citation_from_mods(DOMDocument $mods) {
  module_load_include('inc', 'citeproc', 'CiteProcJSCitation');
  $item = citeproc_item_from_mods($mods);
  $citation = new CiteProcJSCitation();
  $citation->addItem($item);
  return $citation;
}

function citeproc_bibliography_from_mods(CiteProcJSStyle $style, DOMDocument $mods) {
  module_load_include('inc', 'citeproc', 'CiteProcJSBibliography');
  $citation = citeproc_citation_from_mods($mods);
  $bibliography = new CiteProcJSBibliography($style);
  $bibliography->addCitation($citation);
  return $bibliography;
}

function citeproc_style($style) {
  module_load_include('inc', 'csl', 'CSL');
  module_load_include('inc', 'citeproc', 'CiteProcJSStyle');
  $doc = CSL::Get($style);
  if($doc) {
    return new CiteProcJSStyle($doc);
  }
  return FALSE;
}